### ISSUE TITLE
请问登录的账号密码是多少？？

### ISSUE THREAD

**Issue by Davy103** [she1014/GeneralDemo#1]
请问登录的账号密码是多少？？

**Comment by she1014** [comment]
长按登录按钮

**Comment by Davy103** [comment]
提示  “填写信息不能为空！” 噢~~~  好神奇呐

**Comment by Davy103** [comment]
貌似是7.0出现的权限问题喔~~~~
java.lang.SecurityException: MODE_WORLD_WRITEABLE no longer supported
                                                                    at android.app.ContextImpl.checkMode(ContextImpl.java:2326)
                                                                    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:371)
                                                                    at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:366)
                                                                    at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
                                                                    at com.techfly.demo.util.SharePreferenceUtils.<init>(SharePreferenceUtils.java:120)
                                                                    at com.techfly.demo.util.SharePreferenceUtils.getInstance(SharePreferenceUtils.java:113)
                                                                    at com.techfly.demo.activity.user.LoginActivity.defaultLogin(LoginActivity.java:260)
                                                                    at com.techfly.demo.activity.user.LoginActivity$$ViewInjector$6.onLongClick(LoginActivity$$ViewInjector.java:71)
                                                                    at android.view.View.performLongClickInternal(View.java:5726)

**Comment by she1014** [comment]
之前上传的，貌似没有做适配，代码下下来的话，你可以自己加下
